#       0 2 4 6 8 101214
# boom  #       #  #
# crack     #       #
# tick    #   #   #  #
# tss                 #
#
#
#
column_width: 8
pattern_length: 16
bpm: 100

sequences:
  - sound: 'boom'
    steps:
      - 0
      - 8
      - 11  
    column: 0
  - sound: 'crack'
    steps:
      - 4
      - 12
    column: 1
  - sound: 'tick'
    steps:
      - 2
      - 6
      - 10
      - 13
    column: 2
  - sound: 'tsss'
    steps:
      - 14
    column: 2